### ISSUE TITLE
申请加入组织

### ISSUE THREAD

**Issue by fanyu666** [uestcer/community#133]
- 姓名：范宇
- 年级：2020
- 学院：信软
- 方向：嵌入式
- 自我评价：无

**Comment by Xunzhuo** [comment]
@fanyu666 Sent email and check it.

**Comment by fanyu666** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "uestcer/community"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月25日(星期六) 下午2:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [uestcer/community] 申请加入组织 (Issue #133)





 
@fanyu666 Sent email and check it.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
