### ISSUE TITLE
Suggestion for application issue reminder.

### ISSUE THREAD

**Issue by syy11cn** [uestcer/community#137]
@Xunzhuo Hello, Xunzhuo. I see your configuring ci for automatically @ to this repo. If it doesn't work, why not try `Github Assistant` on lark? Here comes the [link](https://www.larksuite.com/hc/zh-CN/articles/360039077593) to it.

By the way, I'm willing to help with the application issues if possible. : )

**Comment by Xunzhuo** [comment]
Thanks for this @syy11cn. In OSS, I suggest using Gitter or Slack to chat with each other.
I have built a online chat room for uestc, but has not managed for so long: https://gitter.im/uestc-community/community

**Comment by syy11cn** [comment]
Gitter is a great choice for chatting. 👍

**Comment by Xunzhuo** [comment]
OK, I will open this issue until I finished this task
