### ISSUE TITLE
申请加入组织！

### ISSUE THREAD

**Issue by DOPAMINE-C** [uestcer/community#144]
Hi! 欢迎加入 UESTC 开源组织 👏，请填写以下信息：

- 姓名：曹马俊
- 年级：2021级
- 学院：自动化学院
- 方向：嵌入式人工智能
- 自我评价：null

**Comment by Xunzhuo** [comment]
Hi，@DOPAMINE-C 请根据 issue 指引，在 [MEMBERS](https://github.com/uestcer/community/blob/master/MEMBERS) 文件末尾加入你的 GitHub id (DOPAMINE-C)
