### ISSUE TITLE
Membership Application

### ISSUE THREAD

**Issue by mo-vic** [uestcer/community#145]
- 姓名：movic
- 年级：研一
- 学院：数学科学学院
- 方向：仍在探索
- 自我评价：To live is to make history!

**Comment by Xunzhuo** [comment]
Hi，@mo-vic 请根据 issue 指引，在 [MEMBERS](https://github.com/uestcer/community/blob/master/MEMBERS) 文件末尾加入你的 GitHub id (mo-vic)，然后提交 PR :)
