### ISSUE TITLE
Membership Application

### ISSUE THREAD

**Issue by wray-lee** [uestcer/community#158]
Hi! 欢迎加入 UESTC 开源组织 👏，请填写以下信息：

- 姓名：柳玉峰
- 年级：2021
- 学院：医学院
- 方向：嵌入式开发
- 自我评价：NULL

⚠️ 提交 Issue 后，请在 [MEMBERS](https://github.com/uestcer/community/blob/master/MEMBERS) 文件末尾加入你的 GitHub ID 并提交 PR，等待 Maintainer 的审核

希望你在开源社区有所收获，UESTCer，互助、共进 :) 👪

**Comment by Xunzhuo** [comment]
Plz send a PR to add your id
